name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.repository == 'akka/akka.io'
    runs-on: ubuntu-20.04
    environment: publish-to-gustav
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Publish
        env:
          GUSTAV_KEY: ${{ secrets.GUSTAV_KEY }}
        run: |+
          eval "$(ssh-agent -s)"
          echo $GUSTAV_KEY | base64 -di > .github/id_rsa
          chmod 600 .github/id_rsa
          scp -i .github/id_rsa -o UserKnownHostsFile=.travis/known_hosts -r _site/* _site/.htaccess akkarepo@gustav.akka.io:akka.io
